### ISSUE TITLE
Use an easy/modern way to maintain rete doc

### ISSUE THREAD

**Issue by xVanTuring** [retejs/rete.js.org#12]
First, thanks for your great project!

Here is it, you need a better way to maintain the doc for rete. I've noticed that you are using hard-coded way to write doc, (which actually is  a bad idea). 
So why not consider using markdown and a doc-generator. For example the official vue.js doc is made by hexo.

Hope it will help.

**Comment by Ni55aN** [comment]
> So why not consider using markdown and a doc-generator

I used Markdown before, it is too limiting

**Comment by xVanTuring** [comment]
Well, that's fine. 
I'll help translate it into Chinese.
