### ISSUE TITLE
English translations are not shown correctly

### ISSUE THREAD

**Issue by Mokkapps** [retejs/rete.js.org#3]
The English translations on the website are not shown correctly, especially in the "Learning" section:

<img width="1276" alt="screenshot 2019-01-25 at 21 43 55" src="https://user-images.githubusercontent.com/3127210/51771752-57dc4400-20ea-11e9-8721-1487d77c01f6.png">

Do you need help with the translations? I can help to implement them but I am no native speaker ;-)

Or does it maybe make sense to just link to: https://rete.readthedocs.io/en/latest/ 

This is the maintained docs version, or?

**Comment by Ni55aN** [comment]
The translations in Docs missing, but we can easily add it as much as possible.

> Do you need help with the translations? I can help to implement them but I am no native speaker 

It'd be cool! I have some problems with grammar in English, so I am in no hurry to translate. 

> Or does it maybe make sense to just link to: https://rete.readthedocs.io/en/latest/

I'm not planning to maintain this

**Comment by Ni55aN** [comment]
I'm using [this](https://github.com/Ni55aN/vue-t9n) plugin for translations. 

[There is](https://github.com/retejs/rete.js.org/blob/master/src/consts/localization/docs/main.js) file for Docs translations, where `first element of items` array - original text from textContent of HTMLElement (or sentence, splitted by adot)

**Comment by Mokkapps** [comment]
Thanks, I am currently working on that. 

One question: How would you structure the translation files, for example for the route `docs/editor`?

**Comment by Ni55aN** [comment]
@Mokkapps I think `docs/editor.js` with import to [index.js](https://github.com/retejs/rete.js.org/blob/master/src/consts/localization/docs/index.js) will be enough

**Comment by Mokkapps** [comment]
I don't get it to work...

I have a `docs/editor.js`:

```javascript
export default [   
    ["Редактор", {
        en: "Editor",
        ua: "Редактор"
    }],
    ["Редактор представляет собой область с узлами и соединениями между их сокетами", {
        en: "The editor is an area with nodes and connections between their sockets",
        ua: "Редактор представляет собой область с узлами и соединениями между их сокетами"
    }]
]
```
and this is the `index.js`:

```javascript
import { assignSection } from '@/i18n';
import main from './main';
import editor from './editor';

export default () => assignSection([
  ...main,
  ...editor
], 'docs');
```

but the translations are not shown for the `/docs/editor` route.

Do you have any idea what I am doing wrong?

**Comment by Ni55aN** [comment]
@Mokkapps the `v-t9n.deep="'docs'"` directive should be added to the root element of component

Example `components/Docs/Editor/index.vue`:
```html
<template lang="pug">
.editor(v-t9n.deep="'docs'")
  h1 Редактор
```

**Comment by Ni55aN** [comment]
I'll add it to all of components

**Comment by Ni55aN** [comment]
Done, now it should works properly

**Comment by Mokkapps** [comment]
@Ni55aN Yes, now it works. Thanks!

**Comment by Mokkapps** [comment]
Okay, I stumbled upon the next issue:

I cannot get this text in `docs/engine`translated:

`В общем случае при каждом изиенении в схеме (узлы, соединения, данные узла) необходимо выполнять обработку`

I tried it this way:

```javascript
["В общем случае при каждом изиенении в схеме (узлы, соединения, данные узла) необходимо выполнять обработку", {
        en: "Consider the situation when, while working in the editor, you need to immediately receive the results of changes (this is easy to do with the 'process' event):",
        ua: "Рассмотрим ситуацию, когда во время работы в редакторе нужно сразу получать результаты изменений (это легко сделать с событием 'process')"
    }],
```

Also, all of the following translations on the page doesn't work, all above worked fine. The whole file at the moment:

```javascript
export default [   
    ["Этот класс позволяет обрабатывать данные на основе потоков в узлах и передавать их из выходных данных во входные", {
        en: "This class allows you to process data based on streams in nodes and transfer them from the output data to the input",
        ua: "Этот класс позволяет обрабатывать данные на основе потоков в узлах и передавать их из выходных данных во входные"
    }],
    ["Движок не зависит от других компонентов редактора", {
        en: "The engine does not depend on other components of the editor",
        ua: "Движок не зависит от других компонентов редактора"
    }],
    ["Все, что ему нужно - это идентификатор, воркеры Компонентов и JSON данные", {
        en: "All he needs is an identifier, component workers and JSON data",
        ua: "Все, что ему нужно - это идентификатор, воркеры Компонентов и JSON данные"
    }],
    ["Он может работать независимо от Редактора", {
        en: "It can work independently from the Editor.",
        ua: "Он может работать независимо от Редактора"
    }],
    ["Обработка", {
        en: "Treatment",
        ua: "Обработка"
    }],
    ["Обход узлов выполняется следующим образом:", {
        en: "Bypassing the nodes is performed as follows:",
        ua: "Обход узлов выполняется следующим образом:"
    }],
    ["Рассмотрим ситуацию, когда во время работы в редакторе нужно сразу получать результаты изменений (это легко сделать с событием 'process')", {
        en: "Consider the situation when, while working in the editor, you need to immediately receive the results of changes (this is easy to do with the 'process' event):",
        ua: "Рассмотрим ситуацию, когда во время работы в редакторе нужно сразу получать результаты изменений (это легко сделать с событием 'process')"
    }],
    ["В общем случае при каждом изиенении в схеме (узлы, соединения, данные узла) необходимо выполнять обработку", {
        en: "Consider the situation when, while working in the editor, you need to immediately receive the results of changes (this is easy to do with the 'process' event):",
        ua: "Рассмотрим ситуацию, когда во время работы в редакторе нужно сразу получать результаты изменений (это легко сделать с событием 'process')"
    }]
]
```

Any idea why it does not work?

**Comment by Ni55aN** [comment]
Yeah, I reproduced it. I'll investigate the issue later, for now I don’t know the reason

**Comment by Mokkapps** [comment]
@Ni55aN Thanks, now I could finish and I have created a PR

**Comment by Ni55aN** [comment]
Another issue that I found:a period and a colon at the end of the sentence were required in translation. Now they are not required

Before: 
```js
["Lorem ipsum:", {}]
```
After: 
```js
["Lorem ipsum", {}]
```
