### ISSUE TITLE
Discord link invalid

### ISSUE THREAD

**Issue by ViniciusFXavier** [retejs/rete.js.org#69]
URL: https://discord.com/invite/cxSFkPZdsV
![image](https://user-images.githubusercontent.com/40774281/231934531-7409c3e6-2437-42cb-9227-4e4f006e1f97.png)

Need new invite link and update all doc locations.

**Comment by Ni55aN** [comment]
This is probably a temporary issue on the Discord side or you need to re-login. I checked the link in incognito tab and it works

**Comment by Ni55aN** [comment]
does the problem still exist?
